### ISSUE TITLE
ModuleNotFoundError: No module named 'Blender-NLA-Midi-Copier-0

### ISSUE THREAD

**Issue by Mumouren** [Cornerback24/Blender-NLA-Midi-Copier#10]
You may have noticed the same issue in the Issue titled "3.2 version".
But I can't solve the problem with the method you mentioned in it.

I'm newly installed in 4.0.2 and try to solve it by update to 4.1.1 and tried to install in 4.0.0 and 3.6.8.
But nothing worked.

Here is the log:
Traceback (most recent call last):
  File "C:\SteamLibrary\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SteamLibrary\steamapps\common\Blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Blender-NLA-Midi-Copier-0'

What deserve to mention is that when I changed the folder's name from "Blender-NLA-Midi-Copier-0.19.0" to "Blender-NLA-Midi-Copier-0" the error changed.

ModuleNotFoundError: No module named 'Blender-NLA-Midi-Copier-0.19

While other part of the log is same.

PS: this happens in Windows 10. I'm not sure if it is a system language problem (I'm using Chinese) 
Thank you.

**Comment by Mumouren** [comment]
Problem solved when running blender in admin mode.
what...

**Comment by Cornerback24** [comment]
Hmm that's interesting.  Thanks for the information. I'll have to think about it and see if it helps me better understand why this happens.
